# render.yaml
services:
  # Backend API Service
  - type: web
    name: helagovi-lk
    env: node
    region: singapore
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      # Add other environment variables in Render dashboard

  # Frontend Web Service (for SPA routing support)
  - type: web
    name: helagovi-lk-frontend
    env: node
    region: singapore
    plan: starter
    buildCommand: |
      cd frontend
      npm install
      npm run build
    startCommand: |
      cd frontend
      npx serve -s dist -l $PORT
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

# Database (if using Render PostgreSQL - optional)
# databases:
#   - name: helagovi-db
#     databaseName: helagovi
#     user: helagovi_user
#     region: singapore
#     plan: starter